// src/lit/input.js
//@ts-check

import { LitElement, html } from 'lit';

class litInput extends LitElement {

    static get properties() {
        return {
            input: {},
            name: {}
        };
    }

    constructor() {
        super();
        this.input = ``;
        this.name = ``;
    }

    inputChanged(e) {
        this.name = e.target.value
            ? `Hello ${e.target.value}`
            : ``;
    }

    render() {
        return html`
            <div>
                <p><strong>Lit Element</strong></p>
                <input value="${this.input}" @input="${this.inputChanged}" placeholder="Please enter your name"/>
                <span>${this.name}</span>
            </div>
        `;
    }

}

customElements.define(`lit-input`, litInput);

// src/svelte/input.svelte
<svelte:options tag="svelte-input"/>

<script>
    // with context (object), greeting is getter
    var input = {
        name: ``,
        get greeting() {
            return this.name ? `Hello, ${this.name}` : ``
        }
    }
    // OR native (me like)
    var name = ``
    $: greeting = name ? `Hello, ${name}` : ``
</script>

<div>
    <p><strong>Svelte Element 1</strong></p>
    <input bind:value={input.name} placeholder="Please enter your name"/>
    <span>{input.greeting}</span>
    <p>or</p>
    <p><strong>Svelte Element 2</strong></p>
    <input bind:value={name} placeholder="Please enter your name"/>
    <span>{greeting}</span>
</div>
